#include "svc.h"

// GetLastError() --> return the most recent error code generated by a windows function that failed 

void    install_svc(char *pathExe)
{
    // handle of service control manager
    SC_HANDLE hSCM = OpenSCManager(NULL, NULL, SC_MANAGER_CREATE_SERVICE);
    if (!hSCM)
    {
        printf("Unable to open SCM: %lu\n", GetLastError());
        return ;
    }

    // handle of specific service
    SC_HANDLE hService = CreateService(
        hSCM,
        SERVICE_NAME,                // intern name of service
        SERVICE_NAME,                // printed name
        SERVICE_ALL_ACCESS,         // all privilege
        SERVICE_WIN32_OWN_PROCESS,  // type of service
        SERVICE_AUTO_START,         // start automatic
        SERVICE_ERROR_NORMAL,       // error gestion
        pathExe,                    // path to executable
        NULL, NULL, NULL, NULL, NULL
    );

    if (!hService)
    {
        // DWORD --> uint32
        DWORD err_code = GetLastError();
        if (err_code == ERROR_SERVICE_EXISTS)
            printf("The service already exists: %lu\n", err_code);
        else
        {
            printf("Cannot create the service: %lu\n", err_code);
            CloseServiceHandle(hSCM);
            return ;
        }
    }
    else
        printf("Service successfully installed\n");

    CloseServiceHandle(hService);
    CloseServiceHandle(hSCM);
    return ;
}